# Generated by Django 3.1.7 on 2021-04-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Keyword', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsearch',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keywordsearch',
            name='end',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keywordsearch',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
