# Generated by Django 3.1.7 on 2021-04-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Keyword', '0002_auto_20210405_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsearch',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='keywordsearch',
            name='start',
            field=models.DateField(blank=True),
        ),
    ]
