# Generated by Django 3.1.7 on 2021-04-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Keyword', '0003_auto_20210405_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsearch',
            name='end',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keywordsearch',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
